### ISSUE TITLE
add test headers

### ISSUE THREAD

**Issue by securelyfitz** [fharding1/tigard#4]
For bitmagic header - BD0..BD5 plus AD0 and AD1 for our 8 pins.

Power and ground testponist.

**Comment by fharding1** [comment]
Do we care about the pinout? Ideally BD0 to BD5 map to 0 through 5 respectively, and then AD0 and AD1 map to 6 and 7, but it would be nice to be able to do whatever is easiest to route.

![image](https://user-images.githubusercontent.com/32021905/84585324-abc0f900-adc3-11ea-9dff-3d7a8c95f18e.png)

**Comment by securelyfitz** [comment]
LA header is a bonus feature likely less frequently used than anything else, so the pin layout is technically a strong preference vs a necessity.

However, I'd **really** prefer that layout, and put it on the [readme](https://github.com/fharding1/tigard#la) 

Second would be AD0,AD1,BD0..BD5, followed by anything that keeps Axx and Bxx contiguous and sequential, followed dead last by anything else.
