### ISSUE TITLE
Clarify VCC/VTGT/TARGET naming convention

### ISSUE THREAD

**Issue by securelyfitz** [fharding1/tigard#9]
Switch is labeled "target", headers are labeled "VCC", LED is labeled "REF", documentation and wiring harnesses i used "VTGT"

It should be consistent. Not sure what it should be. Arguments for each:

VCC: This is what all the pinouts will have it named normally. We label it MOSI not DI or BD2, so why would we make the voltage pin any different?

VTGT: reinforces that you're attaching to someone else's voltage (potentially)

Vx: Clarifies that it's not certain what voltage you're attaching

Switch label: "Target" probably makes sense here; If we go with VCC for the header pins, then the whole switch should probably be labeled the 'VCC selector' or 'Vcc switch' and either Target or TGT is fine.

Once deciding, be sure to update:
- Switch input label
- Switch device label
- Header labels
- LED label
- Jumper wire lables
- Documentation

**Comment by securelyfitz** [comment]
aslo: VREF on the bottom vref/vtarget cuttable jumper.

While i think the easiest answer is to just label everything as it is in the schematic, i'm not sure that's the best answer for the novice end users who might be using the silkscreen text to make decisions.

**Comment by fharding1** [comment]
I'm not a fan of VCC because it's unclear whether you're talking about Tigard's VCC (5v) or the target's VCC (5v, 3.3v, 1.8v, target). I haven't seen Vx before and I think that would just confuse me.

VTGT seems like the best option. It will look a little less elegant on the pinouts but it should be ok.

**Comment by fharding1** [comment]
Is there a label that would make more sense for the jumper on the bottom? VREF/VTGT communicates that while normally the target and reference voltage are the same thing, you can isolate them from each other by cutting the jumper.
